import React,{useMemo,useState}from"react";
import{SafeAreaView,StatusBar,StyleSheet,Text,View,ScrollView,Pressable,TextInput,Alert,Linking}from"react-native";

const C={bg:"#02070d",panel:"#071522",panel2:"#0b1b2b",line:"#19344c",text:"#f7f9fc",muted:"#8fa2b5",red:"#e31b2b",red2:"#a80e19",blue:"#1269a6",gold:"#d7ae67",green:"#2bb673"};
const cats=["8U","9U","10U","11U","12U","13U","14U","15U","16U","17U"];
const teams=["Red Sox","Blue Storm","Black Hawks","Gold Elite"];
const events=[
{name:"Perfect Prospect Showcase",date:"Oct 18",place:"San Juan"},
{name:"Perfect Prospect Mundial",date:"Nov 8",place:"Caguas"},
{name:"Tryout Academia Perfect Prospect",date:"Nov 22",place:"Bayamón"},
{name:"Clínica Perfect Prospect",date:"Dic 6",place:"Carolina"}
];
const shop=[
{name:"Guante",price:149.99},{name:"Bate",price:179.99},{name:"Ropa",price:34.99},{name:"Gorra",price:29.99},{name:"Guantillas",price:39.99},{name:"Protectores",price:59.99},{name:"Equipo de Catcher",price:249.99}
];
const pStats={name:"Carlos Martínez",team:"Red Sox",cat:"14U",pos:"SS",avg:".356",g:26,ab:73,h:26,d2:7,d3:2,hr:5,rbi:21,sb:11};

function Ball({size=88}){return <View style={[s.ball,{width:size,height:size,borderRadius:size/2}]}><View style={[s.seam,{left:size*.22,transform:[{rotate:"65deg"}]}]}/><View style={[s.seam,{right:size*.22,transform:[{rotate:"-65deg"}]}]}/></View>}
function Brand({small=false}){return <View style={s.brandRow}><View style={[s.brandMark,small&&s.brandMarkSmall]}><Text style={[s.brandP,small&&{fontSize:18}]}>PP</Text><View style={s.redSlash}/></View><View><Text style={[s.brandTop,small&&{fontSize:12}]}>PERFECT</Text><Text style={[s.brandBottom,small&&{fontSize:12}]}>PROSPECT</Text></View></View>}
function Atmosphere(){const h=new Date().getHours();const tone=h>=6&&h<16?"day":h>=16&&h<19?"aft":"night";return <View pointerEvents="none" style={StyleSheet.absoluteFill}><View style={[s.sky,tone==="day"?s.skyDay:tone==="aft"?s.skyAft:s.skyNight]}/><View style={s.redGlow}/><View style={s.blueGlow}/><View style={s.lightLeft}/><View style={s.lightRight}/><View style={s.stands}/><View style={s.field}/><View style={s.diamond}/></View>}
function Btn({children,onPress,secondary=false,small=false}){return <Pressable onPress={onPress} style={[s.btn,secondary&&s.btnSecondary,small&&s.btnSmall]}><Text style={[s.btnTxt,secondary&&s.btnSecondaryTxt]}>{children}</Text></Pressable>}
function Card({children,onPress,style}){return <Pressable disabled={!onPress} onPress={onPress} style={[s.card,style]}>{children}</Pressable>}
function Back({onPress}){return <Pressable onPress={onPress} style={s.back}><Text style={s.backTxt}>‹</Text></Pressable>}
function Header({title,onBack}){return <View style={s.header}><Back onPress={onBack}/><Text style={s.headerTitle}>{title}</Text><Brand small/></View>}
function Title({children}){return <Text style={s.title}>{children}</Text>}
function Sub({children}){return <Text style={s.sub}>{children}</Text>}
function Cats({value,setValue}){return <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.cats}>{cats.map(c=><Pressable key={c} onPress={()=>setValue(c)} style={[s.cat,value===c&&s.catOn]}><Text style={[s.catTxt,value===c&&s.catTxtOn]}>{c}</Text></Pressable>)}</ScrollView>}
function Field({label,value,onChangeText,keyboardType}){return <View style={s.fieldBox}><Text style={s.fieldLabel}>{label}</Text><TextInput value={value} onChangeText={onChangeText} keyboardType={keyboardType} placeholder={label} placeholderTextColor="#607386" style={s.input}/></View>}

function Login({enter}){return <SafeAreaView style={s.safe}><StatusBar barStyle="light-content" backgroundColor="#02070d"/><View style={s.login}><Atmosphere/><View style={s.loginBrand}><Brand/><Text style={s.loginLeague}>LEAGUE APP</Text></View><View style={s.loginBall}><Ball size={224}/></View><View style={s.loginButtons}><Btn onPress={enter}>LOG IN</Btn><Btn secondary onPress={enter}>CREATE ACCOUNT</Btn></View></View></SafeAreaView>}

function Home({go}){const tiles=[
["LEAGUE","Teams • Scores • Standings • Stats","LG","league"],
["ACADEMY","Training • Development","AC","academy"],
["EVENTS","Showcases • Tournaments • Clinics","EV","events"],
["PLAYERS","Profiles • Stats • Highlights","PL","players"],
["SCHEDULE","Games • Practices • Events","SC","schedule"],
["PERFECT PROSPECT SHOP","Official Gear","SH","shop"]
];return <ScrollView contentContainerStyle={s.homeScroll}><View style={s.homeHero}><Atmosphere/><View style={s.homeTop}><Brand/><View style={s.bellDot}/></View><View style={s.heroCopy}><Text style={s.heroSmall}>PERFECT PROSPECT</Text><Text style={s.heroBig}>BASEBALL ACADEMY</Text><Text style={s.heroTag}>DISCIPLINE • DEVELOPMENT • OPPORTUNITY</Text></View></View><View style={s.tileGrid}>{tiles.map(([a,b,ic,k])=><Card key={k} onPress={()=>go(k)} style={s.tile}><View style={s.iconBadge}><Text style={s.iconBadgeTxt}>{ic}</Text></View><Text style={s.tileTitle}>{a}</Text><Text style={s.tileSub}>{b}</Text></Card>)}</View><View style={s.develop}><Text style={s.developTxt}>DEVELOPING{`\n`}TOMORROW'S{`\n`}PLAYERS TODAY</Text><Ball size={92}/></View><View style={{height:92}}/></ScrollView>}

function League({go}){const[cat,setCat]=useState("14U");const items=[["LIVE","Escoge categoría y juego","LV","live"],["TEAMS & ROSTERS","Equipos y roster completo","TR","rosters"],["STATISTICS","Equipo y jugador","ST","stats"],["STANDINGS","Posiciones por categoría","TB","standings"],["GPS","Navegar a parques","GP","gps"],["HIGHLIGHTS","Todas las categorías","HL","highlights"]];return <ScrollView contentContainerStyle={s.scroll}><Title>Perfect Prospect League</Title><Cats value={cat} setValue={setCat}/><View style={s.tileGrid}>{items.map(([a,b,ic,k])=><Card key={k} onPress={()=>k==="highlights"?Alert.alert("Highlights","Demo de highlights de todas las categorías."):go(k,{cat})} style={s.tile}><View style={s.iconBadge}><Text style={s.iconBadgeTxt}>{ic}</Text></View><Text style={s.tileTitle}>{a}</Text><Text style={s.tileSub}>{b}</Text></Card>)}</View></ScrollView>}

function Live({cat}){const[game,setGame]=useState(0),[score,setScore]=useState([0,0]),[inning,setInning]=useState(1),[outs,setOuts]=useState(0),[bases,setBases]=useState([false,false,false]);const games=["Red Sox vs Blue Storm","Black Hawks vs Gold Elite"];return <ScrollView contentContainerStyle={s.scroll}><Title>Live • {cat}</Title><View style={s.segment}>{games.map((g,i)=><Pressable key={g} onPress={()=>{setGame(i);setScore([0,0]);setInning(1);setOuts(0);setBases([false,false,false])}} style={[s.seg,game===i&&s.segOn]}><Text style={s.segTxt}>{g}</Text></Pressable>)}</View><Card><Text style={s.centerTitle}>{games[game]}</Text><Text style={s.score}>{score[0]}  -  {score[1]}</Text><Text style={s.centerSub}>Inning {inning} • Outs {outs}</Text><View style={s.baseRow}>{bases.map((b,i)=><Pressable key={i} onPress={()=>setBases(x=>x.map((v,j)=>j===i?!v:v))} style={[s.base,b&&s.baseOn]}><Text style={s.baseTxt}>{i+1}</Text></Pressable>)}</View><View style={s.row}><Btn small onPress={()=>setScore([score[0]+1,score[1]])}>RUN HOME</Btn><Btn small onPress={()=>setScore([score[0],score[1]+1])}>RUN AWAY</Btn></View><View style={s.row}><Btn secondary small onPress={()=>setOuts(Math.min(3,outs+1))}>OUT</Btn><Btn secondary small onPress={()=>{setInning(inning+1);setOuts(0);setBases([false,false,false])}}>NEXT HALF</Btn></View></Card></ScrollView>}

function Rosters({cat}){const staff=["Dirigente • Carlos Rivera","Coach • Miguel Santiago","Coach • José Torres","Coach de pitcheo • Luis Martínez"];return <ScrollView contentContainerStyle={s.scroll}><Title>Teams & Rosters • {cat}</Title>{teams.map(t=><Card key={t}><Text style={s.teamTitle}>{t}</Text>{staff.map(x=><Sub key={x}>{x}</Sub>)}{Array.from({length:15}).map((_,i)=><Text key={i} style={s.rosterLine}>#{i+1}  Jugador {i+1}  •  {i%4===0?"SS":i%4===1?"OF":i%4===2?"RHP":"C"}</Text>)}</Card>)}</ScrollView>}

function Stats({cat}){const[q,setQ]=useState("");const[team,setTeam]=useState("Red Sox");const data=[["G",26],["AVG",".356"],["AB",73],["H",26],["2B",7],["3B",2],["HR",5],["RBI",21],["SB",11]];return <ScrollView contentContainerStyle={s.scroll}><Title>Statistics • {cat}</Title><TextInput value={q} onChangeText={setQ} placeholder="Nombre del jugador" placeholderTextColor={C.muted} style={s.input}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.cats}>{teams.map(t=><Pressable key={t} onPress={()=>setTeam(t)} style={[s.cat,team===t&&s.catOn]}><Text style={[s.catTxt,team===t&&s.catTxtOn]}>{t}</Text></Pressable>)}</ScrollView><Card><Text style={s.teamTitle}>{q||pStats.name}</Text><Sub>{cat} • {team} • SS</Sub><View style={s.statGrid}>{data.map(([a,b])=><View key={a} style={s.statBox}><Text style={s.statNum}>{b}</Text><Text style={s.statLabel}>{a}</Text></View>)}</View><Text style={s.sectionTitle}>Historial acumulado</Text><Sub>4 temporadas • 104 juegos • AVG .338 • 101 hits • 16 HR • 79 RBI • 39 SB</Sub></Card></ScrollView>}

function Standings({cat}){const rows=[["Red Sox","8-2",".800"],["Blue Storm","7-3",".700"],["Black Hawks","6-4",".600"],["Gold Elite","5-5",".500"]];return <ScrollView contentContainerStyle={s.scroll}><Title>Standings • {cat}</Title><Card>{rows.map((r,i)=><View key={r[0]} style={s.tableRow}><Text style={s.rank}>{i+1}</Text><Text style={s.tableTeam}>{r[0]}</Text><Text style={s.tableCell}>{r[1]}</Text><Text style={s.tableCell}>{r[2]}</Text></View>)}</Card></ScrollView>}
function GPS(){const parks=["Parque Julio E. Monagas, Bayamón PR","Parque de Béisbol de Caguas, Caguas PR","Hato Rey Baseball Park, San Juan PR"];return <ScrollView contentContainerStyle={s.scroll}><Title>GPS a Parques</Title>{parks.map(p=><Card key={p}><Text style={s.teamTitle}>{p}</Text><Btn onPress={()=>Linking.openURL(`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(p)}&travelmode=driving`)}>ABRIR EN MAPS</Btn></Card>)}</ScrollView>}

function Academy(){const[step,setStep]=useState(0),[name,setName]=useState(""),[dob,setDob]=useState(""),[pos,setPos]=useState(""),[bat,setBat]=useState(""),[throwing,setThrowing]=useState(""),[guardian,setGuardian]=useState(""),[phone,setPhone]=useState(""),[email,setEmail]=useState(""),[address,setAddress]=useState("");if(step===0)return <ScrollView contentContainerStyle={s.scroll}><Title>Perfect Prospect Academy</Title><Card><Text style={s.centerTitle}>ACADEMY</Text><Sub>Development • Training • Player Progress</Sub><Btn onPress={()=>setStep(1)}>INSCRIBIR JUGADOR</Btn></Card><Card><Text style={s.teamTitle}>Jugadores inscritos</Text><Sub>Progreso, evaluaciones, contrato, recibos y pagos estarán dentro del perfil.</Sub></Card></ScrollView>;if(step===1)return <ScrollView contentContainerStyle={s.scroll}><Title>Inscribir jugador</Title><Field label="Nombre completo" value={name} onChangeText={setName}/><Field label="Fecha de nacimiento" value={dob} onChangeText={setDob}/><Field label="Posición" value={pos} onChangeText={setPos}/><Field label="Batea" value={bat} onChangeText={setBat}/><Field label="Tira" value={throwing} onChangeText={setThrowing}/><Field label="Padre / tutor" value={guardian} onChangeText={setGuardian}/><Field label="Teléfono" value={phone} onChangeText={setPhone} keyboardType="phone-pad"/><Field label="Email" value={email} onChangeText={setEmail} keyboardType="email-address"/><Field label="Dirección" value={address} onChangeText={setAddress}/><Btn onPress={()=>setStep(2)}>CONTINUAR</Btn></ScrollView>;if(step===2)return <ScrollView contentContainerStyle={s.scroll}><Title>Revisar y confirmar</Title><Card><Text style={s.teamTitle}>{name||"Jugador Demo"}</Text><Sub>{dob} • {pos}</Sub><Sub>Batea: {bat} • Tira: {throwing}</Sub><Sub>Tutor: {guardian}</Sub><Sub>{phone} • {email}</Sub><Sub>{address}</Sub><Btn onPress={()=>setStep(3)}>CONFIRMAR</Btn></Card></ScrollView>;if(step===3)return <ScrollView contentContainerStyle={s.scroll}><Title>Pago digital</Title><Card><Text style={s.money}>$100.00</Text><Sub>Mensualidad Academy • Demo</Sub><Btn onPress={()=>setStep(4)}>PAGAR CON TARJETA</Btn><Btn secondary onPress={()=>setStep(4)}>ATH MÓVIL</Btn></Card></ScrollView>;return <ScrollView contentContainerStyle={s.scroll}><Title>Perfil Academy</Title><Card><Text style={s.active}>ACTIVO</Text><Text style={s.teamTitle}>{name||"Jugador Demo"}</Text><Text style={s.playerId}>PP-ACA-000001</Text><View style={s.statGrid}>{[["Exit Velo","82 mph"],["Pitch Velo","76 mph"],["60 yd","7.31"],["Pago","OK"]].map(([a,b])=><View key={a} style={s.statBox}><Text style={s.statNum}>{b}</Text><Text style={s.statLabel}>{a}</Text></View>)}</View><Sub>Coach notes: buen progreso en mecánica, balance y velocidad.</Sub><Btn secondary onPress={()=>Alert.alert("Recibo","Recibo digital demo generado.")}>RECIBO DIGITAL</Btn><Btn secondary onPress={()=>Alert.alert("Contrato","Contrato Academy demo.")}>VER CONTRATO</Btn></Card></ScrollView>}

function Events(){const[selected,setSelected]=useState(null),[name,setName]=useState(""),[cat,setCat]=useState("14U"),[team,setTeam]=useState(""),[guardian,setGuardian]=useState(""),[phone,setPhone]=useState("");if(!selected)return <ScrollView contentContainerStyle={s.scroll}><Title>Special Events</Title>{events.map(e=><Card key={e.name} onPress={()=>setSelected(e)}><Text style={s.teamTitle}>{e.name}</Text><Sub>{e.date} • {e.place}</Sub></Card>)}</ScrollView>;return <ScrollView contentContainerStyle={s.scroll}><Title>{selected.name}</Title><Card><Sub>{selected.date} • {selected.place}</Sub></Card><Text style={s.sectionTitle}>Asistir</Text><Cats value={cat} setValue={setCat}/><Field label="Nombre del jugador" value={name} onChangeText={setName}/><Field label="Equipo" value={team} onChangeText={setTeam}/><Field label="Padre / tutor" value={guardian} onChangeText={setGuardian}/><Field label="Teléfono" value={phone} onChangeText={setPhone}/><Btn onPress={()=>Alert.alert("Registro completado","PP-EVT-000001 • Asistirá")}>ASISTIR</Btn><Btn secondary onPress={()=>setSelected(null)}>OTRO EVENTO</Btn></ScrollView>}

function Players(){const[q,setQ]=useState("");return <ScrollView contentContainerStyle={s.scroll}><Title>Player Center</Title><TextInput value={q} onChangeText={setQ} placeholder="Buscar por nombre" placeholderTextColor={C.muted} style={s.input}/><Card><Text style={s.teamTitle}>{q||pStats.name}</Text><Sub>14U • Red Sox • SS</Sub><Text style={s.playerId}>PP-PLY-000001</Text><View style={s.statGrid}>{[["AVG",".356"],["HR",5],["RBI",21],["SB",11]].map(([a,b])=><View key={a} style={s.statBox}><Text style={s.statNum}>{b}</Text><Text style={s.statLabel}>{a}</Text></View>)}</View><Sub>Historial: 4 temporadas • 104 juegos • AVG .338</Sub></Card><Text style={s.sectionTitle}>Categorías</Text><Cats value={"14U"} setValue={()=>{}}/></ScrollView>}
function Schedule(){return <ScrollView contentContainerStyle={s.scroll}><Title>Schedule</Title><Card><Text style={s.teamTitle}>League</Text><Sub>Sábado 10:00 AM • Red Sox vs Blue Storm</Sub><Sub>Sábado 1:30 PM • Black Hawks vs Gold Elite</Sub></Card><Card><Text style={s.teamTitle}>Academy</Text><Sub>Lunes 5:30 PM • Batting</Sub><Sub>Miércoles 5:30 PM • Defensa y fundamentos</Sub><Sub>Viernes 5:30 PM • Pitching y catchers</Sub><Sub>Sábado 9:00 AM • Evaluaciones y métricas</Sub></Card><Card><Text style={s.teamTitle}>Special Events</Text>{events.map(e=><Sub key={e.name}>{e.date} • {e.name}</Sub>)}</Card></ScrollView>}
function Shop(){const[cart,setCart]=useState([]);const total=cart.reduce((a,b)=>a+b.price,0);return <ScrollView contentContainerStyle={s.scroll}><Title>Perfect Prospect Shop</Title><Card><Text style={s.centerTitle}>OFFICIAL GEAR</Text><Sub>Guantes • Bates • Ropa • Gorras • Guantillas • Protectores • Catcher gear</Sub></Card>{shop.map(p=><Card key={p.name}><View style={s.productRow}><View style={{flex:1}}><Text style={s.teamTitle}>{p.name}</Text><Text style={s.price}>${p.price.toFixed(2)}</Text></View><Btn small onPress={()=>setCart([...cart,p])}>AÑADIR</Btn></View></Card>)}<Card><Text style={s.teamTitle}>Carrito • {cart.length} artículo(s)</Text><Text style={s.money}>${total.toFixed(2)}</Text><Btn onPress={()=>Alert.alert("Checkout","Checkout demo. En producción se conectará un proveedor de pago seguro.")}>CHECKOUT DEMO</Btn></Card></ScrollView>}
function More({go}){return <ScrollView contentContainerStyle={s.scroll}><Title>More</Title><Card onPress={()=>go("players")}><Text style={s.teamTitle}>Players</Text><Sub>Perfiles y estadísticas</Sub></Card><Card><Text style={s.teamTitle}>Notifications</Text><Sub>Alertas y resultados</Sub></Card><Card><Text style={s.teamTitle}>Mi perfil</Text><Sub>Cuenta y preferencias</Sub></Card></ScrollView>}

function BottomNav({go,current}){const items=[["Home","home"],["League","league"],["Academy","academy"],["Events","events"],["More","more"]];return <View style={s.bottomNav}>{items.map(([a,k])=><Pressable key={k} onPress={()=>go(k)} style={s.bottomItem}><View style={[s.bottomDot,current===k&&s.bottomDotOn]}/><Text style={[s.bottomTxt,current===k&&s.bottomTxtOn]}>{a}</Text></Pressable>)}</View>}

export default function App(){const[entered,setEntered]=useState(false),[stack,setStack]=useState([{key:"home",data:{}}]);if(!entered)return <Login enter={()=>setEntered(true)}/>;const current=stack[stack.length-1];const go=(key,data={})=>{if(key==="home"||key==="league"||key==="academy"||key==="events"||key==="more")setStack([{key,data}]);else setStack(x=>[...x,{key,data}])};const back=()=>setStack(x=>x.length>1?x.slice(0,-1):[{key:"home",data:{}}]);let body;if(current.key==="home")body=<Home go={go}/>;else if(current.key==="league")body=<League go={go}/>;else if(current.key==="academy")body=<Academy/>;else if(current.key==="events")body=<Events/>;else if(current.key==="players")body=<Players/>;else if(current.key==="schedule")body=<Schedule/>;else if(current.key==="shop")body=<Shop/>;else if(current.key==="live")body=<Live cat={current.data.cat||"14U"}/>;else if(current.key==="rosters")body=<Rosters cat={current.data.cat||"14U"}/>;else if(current.key==="stats")body=<Stats cat={current.data.cat||"14U"}/>;else if(current.key==="standings")body=<Standings cat={current.data.cat||"14U"}/>;else if(current.key==="gps")body=<GPS/>;else body=<More go={go}/>;const topLevel=["home","league","academy","events","more"].includes(current.key);return <SafeAreaView style={s.safe}><StatusBar barStyle="light-content" backgroundColor={C.bg}/><View style={s.app}>{!topLevel&&<Header title={current.key.toUpperCase()} onBack={back}/>}<View style={{flex:1}}>{body}</View><BottomNav go={go} current={topLevel?current.key:""}/></View></SafeAreaView>}

const s=StyleSheet.create({
safe:{flex:1,backgroundColor:C.bg},app:{flex:1,backgroundColor:C.bg},scroll:{padding:16,paddingBottom:110},homeScroll:{paddingBottom:110,backgroundColor:C.bg},
login:{flex:1,backgroundColor:C.bg,overflow:"hidden"},sky:{position:"absolute",left:0,right:0,top:0,height:"58%"},skyDay:{backgroundColor:"#17304a"},skyAft:{backgroundColor:"#5a271e"},skyNight:{backgroundColor:"#02070d"},redGlow:{position:"absolute",left:-130,top:40,width:300,height:300,borderRadius:180,backgroundColor:"#6b101b",opacity:.45},blueGlow:{position:"absolute",right:-130,top:40,width:300,height:300,borderRadius:180,backgroundColor:"#083f68",opacity:.5},lightLeft:{position:"absolute",left:18,top:55,width:100,height:4,backgroundColor:"#ff404d",opacity:.85},lightRight:{position:"absolute",right:18,top:55,width:100,height:4,backgroundColor:"#42a7ff",opacity:.85},stands:{position:"absolute",left:-40,right:-40,bottom:82,height:180,borderRadius:220,borderWidth:3,borderColor:"#173349",backgroundColor:"#07131e",opacity:.95},field:{position:"absolute",left:0,right:0,bottom:0,height:150,backgroundColor:"#061923"},diamond:{position:"absolute",left:"37%",bottom:30,width:100,height:100,borderWidth:1,borderColor:"#b89f78",transform:[{rotate:"45deg"}],opacity:.25},
brandRow:{flexDirection:"row",alignItems:"center",gap:10},brandMark:{width:82,height:58,borderWidth:2,borderColor:C.gold,borderRadius:12,backgroundColor:"#06111b",alignItems:"center",justifyContent:"center",overflow:"hidden"},brandMarkSmall:{width:48,height:34,borderRadius:8},brandP:{color:C.text,fontWeight:"1000",fontStyle:"italic",fontSize:30,letterSpacing:-4},redSlash:{position:"absolute",right:-14,bottom:-9,width:52,height:24,backgroundColor:C.red,transform:[{rotate:"-30deg"}]},brandTop:{color:C.text,fontWeight:"1000",fontStyle:"italic",fontSize:17,lineHeight:17},brandBottom:{color:C.red,fontWeight:"1000",fontStyle:"italic",fontSize:17,lineHeight:17},
ball:{backgroundColor:"#e6e8e6",borderWidth:1,borderColor:"#9da5a4",shadowColor:"#000",shadowOpacity:.5,shadowRadius:18,elevation:12},seam:{position:"absolute",top:"12%",bottom:"12%",width:2,borderWidth:1,borderColor:"#c4202b",borderStyle:"dashed",borderRadius:20},loginBrand:{position:"absolute",top:85,left:0,right:0,alignItems:"center",gap:12},loginLeague:{color:C.text,letterSpacing:8,fontSize:13,fontWeight:"800"},loginBall:{position:"absolute",left:0,right:0,bottom:145,alignItems:"center"},loginButtons:{position:"absolute",left:24,right:24,bottom:28,gap:10},
btn:{minHeight:50,borderRadius:14,backgroundColor:C.red,alignItems:"center",justifyContent:"center",paddingHorizontal:16,paddingVertical:12,marginTop:10,flex:1},btnSecondary:{backgroundColor:"#07111a",borderWidth:1,borderColor:"#516477"},btnTxt:{color:"#fff",fontWeight:"1000",fontSize:14},btnSecondaryTxt:{color:C.text},btnSmall:{minHeight:42,paddingVertical:9,marginTop:0},
homeHero:{height:360,backgroundColor:C.bg,overflow:"hidden",padding:16},homeTop:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",zIndex:2},bellDot:{width:24,height:24,borderRadius:12,borderWidth:2,borderColor:C.text},heroCopy:{position:"absolute",left:18,bottom:28,zIndex:2},heroSmall:{color:C.text,fontWeight:"900",fontStyle:"italic",fontSize:18},heroBig:{color:"#fff",fontWeight:"1000",fontStyle:"italic",fontSize:34,letterSpacing:-1},heroTag:{marginTop:6,color:"#c8d5df",fontSize:10,fontWeight:"800",letterSpacing:1.5},tileGrid:{flexDirection:"row",flexWrap:"wrap",padding:10,gap:10},card:{backgroundColor:C.panel,borderWidth:1,borderColor:C.line,borderRadius:14,padding:16,marginBottom:12},tile:{width:"48%",minHeight:146,justifyContent:"flex-start"},iconBadge:{width:38,height:38,borderRadius:10,backgroundColor:"#0d2437",borderWidth:1,borderColor:"#315772",alignItems:"center",justifyContent:"center",marginBottom:12},iconBadgeTxt:{color:C.text,fontWeight:"1000",fontSize:12},tileTitle:{color:C.text,fontWeight:"1000",fontSize:14},tileSub:{color:C.muted,fontSize:10,lineHeight:15,marginTop:5},develop:{marginHorizontal:12,marginTop:2,borderRadius:14,borderWidth:1,borderColor:C.line,backgroundColor:"#081722",padding:18,minHeight:138,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},developTxt:{color:"#fff",fontWeight:"1000",fontStyle:"italic",fontSize:22,lineHeight:23},
header:{height:72,borderBottomWidth:1,borderBottomColor:C.line,backgroundColor:"#030a11",flexDirection:"row",alignItems:"center",paddingHorizontal:12,gap:10},back:{width:58,height:58,borderRadius:16,borderWidth:1,borderColor:"#3d5569",backgroundColor:"#071522",alignItems:"center",justifyContent:"center"},backTxt:{color:"#fff",fontSize:42,lineHeight:48},headerTitle:{flex:1,color:C.text,fontSize:18,fontWeight:"1000"},title:{color:C.text,fontSize:24,fontWeight:"1000",marginBottom:14},sub:{color:C.muted,fontSize:12,lineHeight:20},cats:{gap:8,paddingBottom:12},cat:{paddingHorizontal:13,paddingVertical:10,borderRadius:10,borderWidth:1,borderColor:C.line,backgroundColor:C.panel},catOn:{backgroundColor:C.red,borderColor:C.red},catTxt:{color:C.muted,fontWeight:"900",fontSize:12},catTxtOn:{color:"#fff"},
segment:{gap:8,marginBottom:12},seg:{padding:12,borderRadius:10,borderWidth:1,borderColor:C.line,backgroundColor:C.panel},segOn:{backgroundColor:C.red},segTxt:{color:C.text,fontWeight:"900",fontSize:12},centerTitle:{textAlign:"center",color:C.text,fontWeight:"1000",fontSize:20,marginBottom:8},centerSub:{textAlign:"center",color:C.muted,fontWeight:"800"},score:{textAlign:"center",color:"#fff",fontSize:54,fontWeight:"1000",marginVertical:18},baseRow:{flexDirection:"row",justifyContent:"center",gap:20,marginVertical:18},base:{width:44,height:44,borderWidth:2,borderColor:"#52697b",transform:[{rotate:"45deg"}],alignItems:"center",justifyContent:"center",backgroundColor:"#07121b"},baseOn:{backgroundColor:C.gold,borderColor:"#f5d28a"},baseTxt:{color:"#fff",fontWeight:"900",transform:[{rotate:"-45deg"}]},row:{flexDirection:"row",gap:10,marginTop:10},teamTitle:{color:C.text,fontSize:17,fontWeight:"1000",marginBottom:6},rosterLine:{color:"#d4dee6",fontSize:12,paddingVertical:7,borderBottomWidth:1,borderBottomColor:"#102536"},input:{backgroundColor:"#06111b",borderWidth:1,borderColor:C.line,borderRadius:12,color:C.text,paddingHorizontal:13,paddingVertical:12,marginBottom:12},fieldBox:{marginBottom:2},fieldLabel:{color:"#c7d3dd",fontSize:11,fontWeight:"900",marginBottom:6},statGrid:{flexDirection:"row",flexWrap:"wrap",gap:8,marginVertical:14},statBox:{width:"30.5%",backgroundColor:C.panel2,borderRadius:10,borderWidth:1,borderColor:C.line,padding:10,alignItems:"center"},statNum:{color:"#fff",fontSize:18,fontWeight:"1000"},statLabel:{color:C.muted,fontSize:10,fontWeight:"900",marginTop:4},sectionTitle:{color:C.text,fontSize:16,fontWeight:"1000",marginTop:14,marginBottom:8},tableRow:{flexDirection:"row",alignItems:"center",paddingVertical:13,borderBottomWidth:1,borderBottomColor:C.line},rank:{width:32,color:C.gold,fontWeight:"1000",fontSize:18},tableTeam:{flex:1,color:C.text,fontWeight:"900"},tableCell:{width:60,textAlign:"right",color:"#d8e1e8",fontWeight:"800"},money:{color:"#fff",fontSize:36,fontWeight:"1000",textAlign:"center",marginVertical:12},active:{color:C.green,fontWeight:"1000",fontSize:13,marginBottom:8},playerId:{color:C.gold,fontWeight:"900",marginTop:5},productRow:{flexDirection:"row",alignItems:"center",gap:12},price:{color:C.gold,fontSize:18,fontWeight:"1000"},
bottomNav:{position:"absolute",left:0,right:0,bottom:0,minHeight:74,backgroundColor:"#02080e",borderTopWidth:1,borderTopColor:C.line,flexDirection:"row",paddingBottom:10,paddingTop:7},bottomItem:{flex:1,alignItems:"center",justifyContent:"center"},bottomDot:{width:5,height:5,borderRadius:3,backgroundColor:"#405568",marginBottom:6},bottomDotOn:{backgroundColor:C.red,width:18,borderRadius:3},bottomTxt:{color:C.muted,fontSize:10,fontWeight:"800"},bottomTxtOn:{color:"#fff"}
});
